// Mocks generated by Mockito 5.1.0 from annotations
// in faeng_courses/test/app/data/repository/courses_imp_repository_test.dart.
// Do not manually edit this file.

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:faeng_courses/app/data/remote/data_source/courses_rds.dart'
    as _i3;
import 'package:faeng_courses/app/domain/entity/course.dart' as _i4;
import 'package:faeng_courses/app/domain/entity/course_module.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeCollectionReference_0<T extends Object?> extends _i1.Fake
    implements _i2.CollectionReference<T> {}

/// A class which mocks [CoursesRDS].
///
/// See the documentation for Mockito's code generation for more information.
class MockCoursesRDS extends _i1.Mock implements _i3.CoursesRDS {
  MockCoursesRDS() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CollectionReference<_i4.Course> getCoursesReference() =>
      (super.noSuchMethod(Invocation.method(#getCoursesReference, []),
              returnValue: _FakeCollectionReference_0<_i4.Course>())
          as _i2.CollectionReference<_i4.Course>);
  @override
  _i2.CollectionReference<_i5.CourseModule> getCourseModulesReference(
          String? courseId) =>
      (super.noSuchMethod(
              Invocation.method(#getCourseModulesReference, [courseId]),
              returnValue: _FakeCollectionReference_0<_i5.CourseModule>())
          as _i2.CollectionReference<_i5.CourseModule>);
}
